-- PC-side telemetry store (PostgreSQL). Never runs on the robot.
CREATE TABLE IF NOT EXISTS schema_migrations (
    version    INTEGER PRIMARY KEY,
    applied_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE sessions (
    id         UUID PRIMARY KEY,             -- generated by the brain so it can buffer offline
    robot      TEXT NOT NULL,
    started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    ended_at   TIMESTAMPTZ,
    notes      TEXT,
    meta       JSONB NOT NULL DEFAULT '{}'
);

CREATE TABLE frames (
    session_id UUID   NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    seq        BIGINT NOT NULL,              -- frame counter from the robot
    t          DOUBLE PRECISION NOT NULL,    -- robot clock, s
    recv_at    TIMESTAMPTZ NOT NULL,         -- PC wall clock when the frame arrived
    x DOUBLE PRECISION, y DOUBLE PRECISION, theta DOUBLE PRECISION,
    speed      REAL, tank REAL,
    sensors    JSONB NOT NULL,               -- scalar sensors (ultrasonic, flame, gas)
    thermal    REAL[],                       -- 24x32 row-major, only every Nth frame
    est_x REAL, est_y REAL, est_sigma REAL,  -- fused fire estimate
    mode       TEXT,                         -- IDLE / AUTO / GOTO
    cmd_v REAL, cmd_w REAL, cmd_pump BOOLEAN,
    compute_ms REAL,                         -- brain time from frame in to command out
    PRIMARY KEY (session_id, seq)
);
CREATE INDEX frames_recv_at ON frames (recv_at);

CREATE TABLE operator_commands (
    id         BIGSERIAL PRIMARY KEY,
    session_id UUID NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    text       TEXT NOT NULL,
    intent     JSONB,
    valid      BOOLEAN NOT NULL,
    message    TEXT
);

CREATE VIEW v_session_summary AS
SELECT s.id, s.robot, s.started_at, s.ended_at,
       count(f.seq)                   AS frames,
       max(f.t)                       AS robot_seconds,
       min(f.tank)                    AS min_tank,
       coalesce(bool_or(f.cmd_pump), false) AS pumped,
       (SELECT count(*) FROM operator_commands c WHERE c.session_id = s.id) AS operator_commands
FROM sessions s LEFT JOIN frames f ON f.session_id = s.id
GROUP BY s.id;
